AWSTemplateFormatVersion: '2010-09-09'
Description: EventBridge Scheduler for daily brief runs

Parameters:
  RunnerBaseUrl:
    Type: String
    Description: Base URL of the runner service
  SecretArn:
    Type: String
    Description: ARN of the secret containing CRON_SECRET

Resources:
  SchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Ref SecretArn

  DailyBriefScheduleApacBatch0:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: briefs-apac-batch-0
      Description: Daily APAC brief batch 0 at 6:00 AM AWST
      ScheduleExpression: cron(0 22 * * ? *)
      ScheduleExpressionTimezone: UTC
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !Sub "${RunnerBaseUrl}/cron"
        RoleArn: !GetAtt SchedulerRole.Arn
        HttpParameters:
          HeaderParameters:
            Authorization: !Sub "Bearer {{resolve:secretsmanager:${SecretArn}:SecretString:CRON_SECRET}}"
            Content-Type: application/json
        Input: '{"regions":["au"],"runWindow":"apac","scheduled":true,"batchIndex":0,"batchCount":3}'
  DailyBriefScheduleApacBatch1:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: briefs-apac-batch-1
      Description: Daily APAC brief batch 1 at 6:10 AM AWST
      ScheduleExpression: cron(10 22 * * ? *)
      ScheduleExpressionTimezone: UTC
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !Sub "${RunnerBaseUrl}/cron"
        RoleArn: !GetAtt SchedulerRole.Arn
        HttpParameters:
          HeaderParameters:
            Authorization: !Sub "Bearer {{resolve:secretsmanager:${SecretArn}:SecretString:CRON_SECRET}}"
            Content-Type: application/json
        Input: '{"regions":["au"],"runWindow":"apac","scheduled":true,"batchIndex":1,"batchCount":3}'
  DailyBriefScheduleApacBatch2:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: briefs-apac-batch-2
      Description: Daily APAC brief batch 2 at 6:20 AM AWST
      ScheduleExpression: cron(20 22 * * ? *)
      ScheduleExpressionTimezone: UTC
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !Sub "${RunnerBaseUrl}/cron"
        RoleArn: !GetAtt SchedulerRole.Arn
        HttpParameters:
          HeaderParameters:
            Authorization: !Sub "Bearer {{resolve:secretsmanager:${SecretArn}:SecretString:CRON_SECRET}}"
            Content-Type: application/json
        Input: '{"regions":["au"],"runWindow":"apac","scheduled":true,"batchIndex":2,"batchCount":3}'

  DailyBriefScheduleInternationalBatch0:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: briefs-international-batch-0
      Description: Daily international brief batch 0 at 5:00 AM CST
      ScheduleExpression: cron(0 11 * * ? *)
      ScheduleExpressionTimezone: UTC
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !Sub "${RunnerBaseUrl}/cron"
        RoleArn: !GetAtt SchedulerRole.Arn
        HttpParameters:
          HeaderParameters:
            Authorization: !Sub "Bearer {{resolve:secretsmanager:${SecretArn}:SecretString:CRON_SECRET}}"
            Content-Type: application/json
        Input: '{"regions":["us-mx-la-lng"],"runWindow":"international","scheduled":true,"batchIndex":0,"batchCount":3}'
  DailyBriefScheduleInternationalBatch1:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: briefs-international-batch-1
      Description: Daily international brief batch 1 at 5:10 AM CST
      ScheduleExpression: cron(10 11 * * ? *)
      ScheduleExpressionTimezone: UTC
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !Sub "${RunnerBaseUrl}/cron"
        RoleArn: !GetAtt SchedulerRole.Arn
        HttpParameters:
          HeaderParameters:
            Authorization: !Sub "Bearer {{resolve:secretsmanager:${SecretArn}:SecretString:CRON_SECRET}}"
            Content-Type: application/json
        Input: '{"regions":["us-mx-la-lng"],"runWindow":"international","scheduled":true,"batchIndex":1,"batchCount":3}'
  DailyBriefScheduleInternationalBatch2:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: briefs-international-batch-2
      Description: Daily international brief batch 2 at 5:20 AM CST
      ScheduleExpression: cron(20 11 * * ? *)
      ScheduleExpressionTimezone: UTC
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !Sub "${RunnerBaseUrl}/cron"
        RoleArn: !GetAtt SchedulerRole.Arn
        HttpParameters:
          HeaderParameters:
            Authorization: !Sub "Bearer {{resolve:secretsmanager:${SecretArn}:SecretString:CRON_SECRET}}"
            Content-Type: application/json
        Input: '{"regions":["us-mx-la-lng"],"runWindow":"international","scheduled":true,"batchIndex":2,"batchCount":3}'
