const KEYWORD_MAP: Record<string, string[]> = {
  "rigs-integrated-drilling": [
    "rig",
    "dayrate",
    "tender",
    "jack-up",
    "jackup",
    "semisub",
    "drillship",
    "MODU",
    "rig count",
    "utilization",
    "BOP",
    "well control"
  ],
  "drilling-services": [
    "directional",
    "MWD",
    "LWD",
    "mud logging",
    "drilling fluids",
    "cementing",
    "drill bit",
    "RSS",
    "BHA",
    "fishing",
    "wellsite geology"
  ],
  "wells-materials-octg": [
    "OCTG",
    "casing",
    "tubing",
    "line pipe",
    "CRA",
    "alloy",
    "premium connection",
    "wellhead",
    "tree",
    "valves",
    "flanges",
    "fittings",
    "bolting",
    "gaskets",
    "NACE"
  ],
  "completions-intervention": [
    "wireline",
    "slickline",
    "e-line",
    "coiled tubing",
    "stimulation",
    "frac",
    "acidizing",
    "perforating",
    "sand control",
    "flowback",
    "well test",
    "workover",
    "intervention"
  ],
  "pa-decommissioning": [
    "decommissioning",
    "plug and abandonment",
    "P&A",
    "abandonment",
    "removal",
    "topsides",
    "subsea removal",
    "dismantling",
    "recycling",
    "remediation"
  ],
  "subsea-surf-offshore": [
    "subsea",
    "SURF",
    "umbilical",
    "riser",
    "flowline",
    "manifold",
    "tree",
    "IMR",
    "ROV",
    "pipelay",
    "trenching",
    "tie-in",
    "offshore construction"
  ],
  "projects-epc-epcm-construction": [
    "EPC",
    "EPCM",
    "FEED",
    "construction",
    "commissioning",
    "fabrication",
    "module",
    "capex",
    "project controls",
    "brownfield",
    "greenfield"
  ],
  "major-equipment-oem-ltsa": [
    "turbine",
    "compressor",
    "pump",
    "generator",
    "LTSA",
    "OEM",
    "overhaul",
    "spares",
    "vibration",
    "condition monitoring",
    "switchgear",
    "transformer"
  ],
  "ops-maintenance-services": [
    "maintenance",
    "turnaround",
    "shutdown",
    "scaffolding",
    "rope access",
    "NDT",
    "inspection",
    "corrosion",
    "painting",
    "coatings",
    "reliability",
    "integrity"
  ],
  "mro-site-consumables": [
    "valves",
    "gaskets",
    "bolting",
    "fasteners",
    "fittings",
    "flanges",
    "PPE",
    "hoses",
    "filters",
    "bearings",
    "seals",
    "distributor",
    "catalogue"
  ],
  "logistics-marine-aviation": [
    "freight",
    "shipping",
    "marine",
    "PSV",
    "AHTS",
    "port",
    "customs",
    "3PL",
    "warehousing",
    "trucking",
    "air cargo",
    "helicopter",
    "bunker fuel"
  ],
  "site-services-facilities": [
    "catering",
    "camp",
    "accommodation",
    "facilities",
    "cleaning",
    "laundry",
    "security",
    "waste",
    "HVAC",
    "SLA"
  ],
  "it-telecom-cyber": [
    "cybersecurity",
    "ransomware",
    "vulnerability",
    "patch",
    "identity",
    "zero trust",
    "OT",
    "ICS",
    "SCADA",
    "DCS",
    "cloud",
    "SaaS",
    "telecom",
    "satcom"
  ],
  "professional-services-hr": [
    "HR",
    "recruitment",
    "staffing",
    "consulting",
    "advisory",
    "legal",
    "audit",
    "tax",
    "accounting",
    "L&D",
    "training",
    "change management"
  ]
};

/**
 * Returns prioritized keywords for a portfolio used in ranking ingestion candidates.
 * @param portfolioSlug portfolio identifier
 */
export function keywordsForPortfolio(portfolioSlug: string): string[] {
  return KEYWORD_MAP[portfolioSlug] ?? [];
}
